DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS teachers;

CREATE TABLE students(
	id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255));
CREATE TABLE teachers(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255));